- app/models/address.rb
- app/models/cart_item.rb
- app/models/gener.rb
- app/models/item.rb
- app/models/oder.rb
- app/models/oder_detail.rb
- db/migrate/20220316081324_create_items.rb
- db/migrate/20220316081415_create_geners.rb
- db/migrate/20220316081424_create_oders.rb
- db/migrate/20220316081440_create_cart_items.rb
- db/migrate/20220316081500_create_oder_details.rb
- db/migrate/20220316081521_create_addresses.rb
- db/schema.rb
- test/fixtures/addresses.yml
- test/fixtures/cart_items.yml
- test/fixtures/geners.yml
- test/fixtures/items.yml
- test/fixtures/oder_details.yml
- test/fixtures/oders.yml
- test/models/address_test.rb
- test/models/cart_item_test.rb
- test/models/gener_test.rb
- test/models/item_test.rb
- test/models/oder_detail_test.rb
- test/models/oder_test.rb
> Model create 

- Gemfile
- Gemfile.lock
- app/javascript/packs/application.js
- app/javascript/stylesheets/application.scss
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/views/layouts/application.html.erb
- config/initializers/kaminari_config.rb
- config/webpack/environment.js
- db/migrate/20220317005413_create_active_storage_tables.active_storage.rb
- db/schema.rb
- package.json
- yarn.lock
ActiveStorage
Bootstarap
FontAwesome
Kaminari
jquery
追加しました。
確認お願いします。
> [add-gemfile]

- app/models/gener.rb
- app/models/genre.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_detail.rb
> Create associaton ジャンルのアソシエーション

- config/routes.rb
> [Add]ルーディング設定

- app/controllers/admin/genres_controller.rb
- app/models/genre.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- config/environments/development.rb
- config/webpack/environment.js
- db/schema.rb
確認お願いします。
ジャンルは「ケーキ」と「プリン」の二種類を登録してあります。
> Admin genre

- app/controllers/admin/items_controller.rb
- app/models/item.rb
- app/views/admin/items/index.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/sessions/new.html.erb
- config/environments/development.rb
- config/routes.rb
- db/schema.rb
> [Add]新規商品登録、商品一覧

- app/views/layouts/application.html.erb
- app/views/public/registrations/new.html.erb
- package.json
- yarn.lock
> [fix]bootstrap

- app/models/item.rb
- app/views/admin/items/new.html.erb
- app/views/admin/items/show.html.erb
> [Add]商品詳細画面・商品編集画面

- app/views/layouts/application.html.erb
- app/views/public/registrations/new.html.erb
> [Fix]sign_up

- Gemfile
- Gemfile.lock
- app/controllers/admin/items_controller.rb
- app/models/item.rb
- app/views/admin/items/_form.html.erb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/new.html.erb
- config/application.rb
- config/locales/ja.yml
> Admin items create

- app/controllers/public/customers_controller.rb
- app/views/public/addresses/edit.html.erb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/customers/unsubscribe.html.erb
- config/routes.rb
> Public customer

- app/controllers/admin/customers_controller.rb
- app/controllers/application_controller.rb
- app/models/genre.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- config/webpack/environment.js
- db/schema.rb
> Create admin customer

- app/controllers/admin/items_controller.rb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/index.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/items/show.html.erb
- config/webpack/environment.js
> [Add]商品関係編集

- app/controllers/public/cart_items_controller.rb
- app/controllers/public/items_controller.rb
- app/models/cart_item.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- config/routes.rb
> Cart item create

- app/controllers/admin/orders_controller.rb
- app/controllers/public/orders_controller.rb
- app/models/order.rb
- app/views/admin/orders/index.html.erb
- app/views/admin/orders/show.html.erb
- app/views/layouts/_header.html.erb
- app/views/public/orders/show.html.erb
Reverts takoyaki-revengers/nagano_cake#40
> Revert "Admin header"

- app/controllers/public/orders_controller.rb
- app/models/order.rb
- app/views/public/orders/index.html.erb
- app/views/public/orders/show.html.erb
> Public orders2

- app/views/layouts/_footer.html.erb
- app/views/public/homes/top.html.erb
> [add]フッターやりかけ

- app/views/admin/customers/index.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/items/index.html.erb
- app/views/layouts/_header.html.erb
> [fix]ジャンルのデザイン修正

- app/views/admin/customers/index.html.erb
> [Fix]admin-index.html

- app/models/genre.rb
> [Add]ジャンル登録　バリデーション

- app/controllers/admin/items_controller.rb
- app/models/item.rb
- app/views/layouts/_footer.html.erb
> [fix]管理者バリデーション

- app/views/admin/orders/show.html.erb
> [Fix-layout]管理者側の注文履歴詳細

- app/controllers/admin/customers_controller.rb
- app/controllers/admin/order_details_controller.rb
- app/controllers/admin/orders_controller.rb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/admin/orders/show.html.erb
・注文ステータス、制作ステータスの更新メッセージ追加
・管理者側の会員ステータス切り替え
確認お願いします！
> Admin order status message

- config/locales/devise.ja.yml
deviseのフラッシュメッセージ変更
サインイン→ログイン　などに変更しました。
> [fix]deviseのフラッシュメッセージ変更

- app/controllers/public/customers_controller.rb
- app/models/customer.rb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
> Fix public customer

- Gemfile
- Gemfile.lock
- config/locales/devise.ja.yml
- config/locales/devise.views.ja.yml
> [add]gem 'devise-i18n'の導入

- app/assets/stylesheets/application.scss
- app/views/layouts/_footer.html.erb
> [fix]フッター調整

- app/controllers/admin/genres_controller.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/show.html.erb
注文履歴一覧ボタンの遷移先などを修正しました。
確認お願いします。
> Admin layout
